---
title: "jmBIG"
output: 
  flexdashboard::flex_dashboard:
  social: menu
source_code: embeded
runtime: shiny    
---
  
  
  
```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(jmBIG)
library(survival)
library(dplyr)
library(jmBIG)
library(ggplot2)
library(FastJM)
library(JMbayes2)
library(lme4)
library(rstanarm)
library(joineRML)
```



Introduction
=====================================  
  
  Column {data-width=1000}
-------------------------------------
  
```{r}
shinyApp(
  ui_page1 <- fluidPage(
    titlePanel("jmBIG: An R package for joint model for BIG data"),
    sidebarLayout(
      sidebarPanel(
        h3("jmBIG"),
        h5("Developed by :"),
        h6("Atanu Bhattacharjee"),
        h6("Bhrigu Kumar Rajbongshi"),
        h6("Gajendra K Vishwakarma"),
        p('Download jmBIG package from'),
        a("https://cran.r-project.org/web/packages/jmBIG/index.html",
          href = "https://cran.r-project.org/web/packages/jmBIG/index.html")
      ),
      mainPanel(
        h3("Introduction"),
        p("Provides analysis tools for big data where the sample size is very large. It offers a suite of functions for fitting and predicting joint models, which allow for the simultaneous analysis of longitudinal and time-to-event data. This statistical methodology is particularly useful in medical research where there is often interest in understanding the relationship between a longitudinal biomarker and a clinical outcome, such as survival or disease progression. This can be particularly useful in a clinical setting where it is important to be able to predict how a patient's health status may change over time. Overall, this package provides a comprehensive set of tools for joint modeling of BIG data obtained as survival and longitudinal outcomes with both Bayesian and non-Bayesian approaches. Its versatility and flexibility make it a valuable resource for researchers in many different fields, particularly in the medical and health sciences."),
        p("The package mainly consist of four functions which are derived from for different package JMbayes2, FastJM,  rstanarm and joineRML. Each package has its own estimation procedure and prediction capacity. The main objective of our package jmBIG is to offer a compact pack of tools which could be used for BIG-Data( dataset with a extremely large number of rows. In each of the function there are mainly three components: Longitudinal model, survival model and sample size. The longitudinal model part is divided into two arguments in some functions one for the fixed effect part and other for the random effect part like y~1+x1 and ~1|id, if we consider a random intercept at individual level. The survival model input is kept as we use in R code like Surv(time,status)~x1+x2. The input option- sample size basically divides the entire dataset into several chunk and fits the model in each chunk and provides an output for the BIGdata. It is a subjective choice for the user.
          The other arguments such as nchain( number of MCMC chain), name of observation time variable, name of id variable ,name of column to represent visit of subject etc. are obtained from the uploaded dataset or the default dataset in this example shiny app. A glimps of the default longitudinal and survival data used in this app which are available in our jmBIG package is shown below :"),
     verbatimTextOutput('exampledatalong'),
     verbatimTextOutput('exampledatasurv')
        
      )
    )
  ),
  server_page1 <- function(input, output, session) {
    # No server logic defined for this page
     output$exampledatalong <- renderPrint({
       #cat('First 10 rows of default Longitudinal data')
      long2[long2$id<5,]
    })
     output$exampledatasurv <- renderPrint({
       #cat('First 10 rows of default Survival data')
      #req(surv2)
      surv2[surv2$id<5,]
    })
     
  },
  options = list(height=1000,width="100%")
)
```

jmBayesBIG
=====================================  
  
  Column {data-width=1000}
-------------------------------------
  
```{r}
shinyApp(
  ui_page2 <- fluidPage(
    
    titlePanel("jmbayesBig"),
    
    sidebarLayout(
      sidebarPanel(
        radioButtons("data_option_page2", "Select data source:",
                     c("Upload your own dataset" = "upload",
                       "Use default dataset from jmBIG" = "default")),
        conditionalPanel(
          condition = "input.data_option_page2== 'default'",
          sliderInput("pid_page2", "ID", min = min(surv2$id), max = max(surv2$id), value = 50)
        ),
        conditionalPanel(
          condition = "input.data_option_page2 == 'upload'",
          fileInput("lfile_page2", "Upload Longitudinal Data (CSV format)"),
          fileInput("sfile_page2", "Upload Survival Data (CSV format)"), 
          uiOutput("pid_slider_upload_page2")
        ),
        selectInput("idvar_page2", "ID variable", choices =NULL),
        selectInput("timevar_page2", "Visit time", choices = NULL),
        selectInput('obs_time_page2',"Survival Time variable",choices=NULL),
        selectInput("event_page2", "Event status", choices = NULL),
        textInput("longmodel_page2", "Longitudinal data model", value = "y~1+x7"),
        textInput("rdmodel_page2", "Longitudinal data model random effect part", value = "~visit|id"),
        textInput("survmodel_page2", "Survival data model", value = "Surv(time,status)~1+x1"),
        numericInput("nchain_page2", "Number of chain", value = 1),
        numericInput("samplesize_page2", "Loop size", value = 200),
        actionButton("submit_page2", "Submit")
      ),
      mainPanel(
        p('jmbayesBig(): a function for joint model in BIG DATA using JMbayes2 package. For more information about the arguments of the function please look ',a("here.",
                                                                                                                                                                 href = "https://cran.r-project.org/web/packages/jmBIG/index.html")),
        textOutput('selected_var_page2'),
        textOutput('sample_size_page2'),
        verbatimTextOutput('summarylmemodel_page2'),
        textOutput('selectedID'),
        plotOutput('postTajectory'),
        plotOutput('postSurvival')
        #tabPanel(Title='summary',verbatimTextOutput('summarylmemodel_page2')),
        #tabPanel(Title="Plot",plotOutput('summarylmemodel_page21',width='50%'))
        
        
      )
    )
    
  ),
  server_page2 <- function(input, output, session) {
    
    
    
    
    defaultsurvdata_page2 <- reactive({
      if (input$data_option_page2 == 'upload') {
        req(input$sfile_page2)
        defaultsurvdata_page2 <- read.csv(input$sfile_page2$datapath)
      } else {
        defaultsurvdata_page2 <- surv2
      }
      return(defaultsurvdata_page2)
    })
    observeEvent(defaultsurvdata_page2(), {
      updateSelectInput(session, "idvar_page2", choices = names(defaultsurvdata_page2()))
      updateSelectInput(session, "timevar_page2", choices = names(defaultsurvdata_page2()))
      updateSelectInput(session, "event_page2", choices = names(defaultsurvdata_page2()))
      updateSelectInput(session, "obs_time_page2", choices = names(defaultsurvdata_page2()))
    })
    
    
    
    defaultlongdata_page2 <- reactive({
      if (input$data_option_page2 == 'upload') {
        req(input$lfile_page2)
        defaultlongdata_page2 <- read.csv(input$lfile_page2$datapath)
      } else {
        defaultlongdata_page2 <- long2
      }
      return(defaultlongdata_page2)
    })
    
    # Render PID slider for uploaded data
    output$pid_slider_upload_page2 <- renderUI({
      req(input$idvar_page2)
      tagList(
        selectInput("pid_page22", "Patient ID", choices=defaultsurvdata_page2()[[input$idvar_page2]],selectize = FALSE,size=5)
      )
    })
    
    output$selected_var_page2 <- reactive({
      
      if (input$data_option_page2 == "default") {
        req(input$pid_page2)
        paste("You have selected patient ID", input$pid_page2)
      } else {
        req(input$pid_page22)
        paste("Uploaded data selected with patient ID",input$pid_page22)
      }
    })
    
    output$selectedID <- reactive({
      
      if (input$data_option_page2 == "default") {
        req(input$pid_page2)
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmbayesBig() for the selected patient ID: ',input$pid_page2)
      } else {
        req(input$pid_page22)
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmbayesBig() for the selected patient ID: ',input$pid_page22)
      }
    })
    
    
    output$sample_size_page2 <- renderText({
      paste("Loop size for this computation is", input$samplesize_page2)
    })
    
    rv<-reactiveValues(model_page2=NULL)
    
    observeEvent(input$submit_page2,{
      # Load default data
      output$summarylmemodel_page2 <- renderPrint({
        req(input$samplesize_page2)
        req(input$nchain_page2)
        req(input$timevar_page2)
        req(input$idvar_page2)
        
        rdmodel2<-as.formula(input$rdmodel_page2)
        longmodel2<-as.formula(input$longmodel_page2)
        survmodel2<-as.formula(input$survmodel_page2)
        
        fitmodel_page22 <- jmbayesBig(dtlong = defaultlongdata_page2(), dtsurv = defaultsurvdata_page2(),
                                      longm =longmodel2, survm = survmodel2, rd = rdmodel2,
                                      timeVar = input$timevar_page2, nchain = input$nchain_page2,
                                      samplesize = input$samplesize_page2,
                                      id = input$idvar_page2)
        rv$model_page2<-fitmodel_page22
        fitmodel_page22$pseudoMod
        # list(head(defaultlongdata_page2()),head(defaultsurvdata_page2()),
        #      longmodel2,survmodel2,rdmodel2,input$timevar_page2,input$nchain_page2,
        #      input$samplesize_page2,input$idvar_page2)
        
      })
      
    })
    
    observeEvent(input$submit_page2,{
      # Load default data
      output$postTajectory<- renderPlot({
        
        if(input$data_option_page2 == "default"){
          req(input$samplesize_page2)
          req(input$nchain_page2)
          req(input$timevar_page2)
          req(input$idvar_page2)
          req(input$pid_page2)
          
          idvar_page22<-input$idvar_page2
          pid_page22<-input$pid_page2
          ydt<-defaultlongdata_page2()[defaultlongdata_page2()[idvar_page22]==pid_page22,]
          cdt<-defaultsurvdata_page2()[defaultsurvdata_page2()[idvar_page22]==pid_page22,]
          newdata<-ydt[ydt[input$idvar_page2]==pid_page22,]
          P2_long<-predJMbayes(model=rv$model_page2,ids=pid_page22,newdata=newdata,process = 'longitudinal')
          #head(P2_long$p1[[1]]) 
          plot(P2_long$p1[[1]])
        }else{
          req(input$samplesize_page2)
          req(input$nchain_page2)
          req(input$timevar_page2)
          req(input$idvar_page2)
          req(input$pid_page22)
          
          idvar_page22<-input$idvar_page2
          pid_page221<-input$pid_page22
          ydt<-defaultlongdata_page2()[defaultlongdata_page2()[idvar_page22]==pid_page221,]
          cdt<-defaultsurvdata_page2()[defaultsurvdata_page2()[idvar_page22]==pid_page221,]
          #list(head(defaultsurvdata_page2()),cdt,pid_page221)
          #newdata<-full_join(ydt,cdt,by=idvar_page22)
          #head(newdata)
          newdata<-ydt[ydt[input$idvar_page2]==pid_page221,]
          P2_long<-predJMbayes(model=rv$model_page2,ids=pid_page221,newdata=newdata,process = 'longitudinal')
          #head(P2_long$p1[[1]]) 
          plot(P2_long$p1[[1]])
        }
        
      })
      
    })
    
    observeEvent(input$submit_page2,{
      # Load default data
      output$postSurvival<- renderPlot({
        
        if(input$data_option_page2 == "default"){
          req(input$samplesize_page2)
          req(input$nchain_page2)
          req(input$timevar_page2)
          req(input$idvar_page2)
          req(input$pid_page2)
          
          idvar_page22<-input$idvar_page2
          pid_page22<-input$pid_page2
          ydt<-defaultlongdata_page2()[defaultlongdata_page2()[idvar_page22]==pid_page22,]
          cdt<-defaultsurvdata_page2()[defaultsurvdata_page2()[idvar_page22]==pid_page22,idvar_page22]
          #list(dim(ydt),dim(cdt))
          newdata<-ydt
          #newdata
          P2_event<-predJMbayes(model=rv$model_page2,ids=pid_page22,newdata=newdata,process = 'event')
          #P2_long<-predJMbayes(model=rv$model_page2,ids=pid_page22,newdata=newdata,process = 'longitudinal')
          plot(P2_event$p1[[1]])
          #plot(P2_long$p1[[1]])
        }else{
          req(input$samplesize_page2)
          req(input$nchain_page2)
          req(input$timevar_page2)
          req(input$idvar_page2)
          req(input$pid_page22)
          
          idvar_page22<-input$idvar_page2
          pid_page221<-input$pid_page2
          ydt<-defaultlongdata_page2()[defaultlongdata_page2()[idvar_page22]==pid_page221,]
          cdt<-defaultsurvdata_page2()[defaultsurvdata_page2()[idvar_page22]==pid_page221,]
          #list(dim(ydt),dim(cdt))
          newdata<-ydt
          #newdata
          P2_event<-predJMbayes(model=rv$model_page2,ids=pid_page221,newdata=newdata,process = 'event')
          #P2_long<-predJMbayes(model=rv$model_page2,ids=pid_page22,newdata=newdata,process = 'longitudinal')
          #plot(P2_event$p1[[1]])
          plot(P2_event$p1[[1]])
          
        }
      })
      
    })
    
    
    
    
  },
  options = list(height=1000,width="100%")
)
```

joinrmlBIG
=====================================  
  
  Column {data-width=1000}
-------------------------------------
  
```{r}
shinyApp(
  ui_page4 <- fluidPage(
    
    titlePanel("joinRMLBig"),
    
    sidebarLayout(
      sidebarPanel(
        radioButtons("data_option_page4", "Select data source:",
                     c("Upload your own dataset" = "upload",
                       "Use default dataset from jmBIG" = "default")),
        conditionalPanel(
          condition = "input.data_option_page4== 'default'",
          sliderInput("pid_page4", "ID", min = min(surv2$id), max = max(surv2$id), value = 50)
        ),
        conditionalPanel(
          condition = "input.data_option_page4== 'upload'",
          fileInput("lfile_page4", "Upload Longitudinal Data (CSV format)"),
          fileInput("sfile_page4", "Upload Survival Data (CSV format)"), 
          uiOutput("pid_slider_upload_page4")
        ),
        selectInput("idvar_page4", "ID variable", choices =NULL),
        selectInput("timevar_page4", "Visit time", choices = NULL),
        selectInput('obs_time_page4',"Survival Time variable",choices=NULL),
        selectInput("event_page4", "Event status", choices = NULL),
        textInput("longmodel_page4", "Longitudinal data model", value = "y~1+x7"),
        textInput("rdmodel_page4", "Longitudinal data model random effect part", value = "~1|id"),
        textInput("survmodel_page4", "Survival data model", value = "Surv(time,status)~1+x1"),
        numericInput("samplesize_page4", "Loop size", value = 200),
        actionButton("submit_page4", "Submit")
      ),
      mainPanel(
        p('joinRMLBig(): a function for joint model in BIG DATA using joineRML package. For more information about the arguments of the function please look ',a("here.",
                                                                                                                                                                 href = "https://cran.r-project.org/web/packages/jmBIG/index.html")),
        
        textOutput('selected_var_page4'),
        textOutput('sample_size_page4'),
        verbatimTextOutput('summarylmemodel_page4'),
        textOutput('selectedID'),
        plotOutput('postTajectory'),
        #downloadButton("postTajectory_plot", "Download Plot"),
        plotOutput('postSurvival')
        #downloadButton("postSurvival_plot", "Download Plot")
      )
    )
    
  ),
  server_page4 <- function(input, output, session) {
    
    
    rv<-reactiveValues(model_page4=NULL,longdata_page4=NULL,survdata_page4=NULL)
    defaultsurvdata_page4 <- reactive({
      #defaultsurvdata_page4<-NULL
      if (input$data_option_page4 == 'upload') {
        req(input$sfile_page4)
        defaultsurvdata_page4 <- read.csv(input$sfile_page4$datapath)
      } else {
        defaultsurvdata_page4 <- surv2
      }
      #rv$survdata_page4<-defaultsurvdata_page4
      defaultsurvdata_page4
    })
    
    
    observeEvent(defaultsurvdata_page4(), {
      updateSelectInput(session, "idvar_page4", choices = names(defaultsurvdata_page4()))
      updateSelectInput(session, "timevar_page4", choices = names(defaultsurvdata_page4()))
      updateSelectInput(session, "event_page4", choices = names(defaultsurvdata_page4()))
      updateSelectInput(session, "obs_time_page4", choices = names(defaultsurvdata_page4()))
    })
    
    
    defaultlongdata_page4 <- reactive({
      #defaultlongdata_page4<-NULL
      if (input$data_option_page4 == 'upload') {
        req(input$lfile_page4)
        defaultlongdata_page4 <- read.csv(input$lfile_page4$datapath)
      } else {
        defaultlongdata_page4 <- long2
      }
      #rv$longdata_page4<-defaultlongdata_page4
      defaultlongdata_page4
    })
    
    # Render PID slider for uploaded data
    output$pid_slider_upload_page4 <- renderUI({
      req(input$idvar_page4)
      tagList(
        selectInput("pid_page44", "Patient ID", choices = defaultsurvdata_page4()[[input$idvar_page4]],selectize = FALSE,size=5)
      )
    })
    
    output$selected_var_page4 <- reactive({
      
      if (input$data_option_page4 == "default") {
        req(input$pid_page4)
        paste("You have selected patient ID", input$pid_page4)
      } else {
        req(input$pid_page44)
        paste("Uploaded data selected with patient ID ",input$pid_page44)
      }
    })
    
    
    
    output$selectedID <- reactive({
      
      if (input$data_option_page4 == "default") {
        req(input$pid_page4)
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using joinRMLBig() for the selected patient ID: ', input$pid_page4)
      } else {
        req(input$pid_page44)
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using joinRMLBig() for the selected patient ID: ',input$pid_page44)
      }
    })
    
    output$sample_size_page4 <- renderText({
      paste("Loop size for this computation is", input$samplesize_page4)
    })
    
    
    
    observeEvent(input$submit_page4,{
      # Load default data
      output$summarylmemodel_page4 <- renderPrint({
        req(input$samplesize_page4)
        req(input$longmodel_page4)
        req(input$survmodel_page4)
        req(input$rdmodel_page4)
        req(input$timevar_page4)
        req(input$idvar_page4)
        #req(defaultlongdata_page4())
        #req(defaultsurvdata_page4())
        
        rdmodel4<-as.formula(input$rdmodel_page4)
        longmodel4<-as.formula(input$longmodel_page4)
        survmodel4<-as.formula(input$survmodel_page4)
        
        fitmodel_page4 <- joinRMLBig(dtlong = defaultlongdata_page4(), dtsurv = defaultsurvdata_page4(),
                                     longm = longmodel4, survm = survmodel4, rd = rdmodel4,
                                     timeVar = input$timevar_page4, samplesize = input$samplesize_page4,
                                     id = input$idvar_page4)
        rv$model_page4<-fitmodel_page4
        jmBIG::print(fitmodel_page4)
        #list(dim(defaultlongdata_page4()))
        
      })
      
    })
    
    observeEvent(input$submit_page4,{
      output$postTajectory<-renderPlot({
        
        if(input$data_option_page4 == "default"){
          req(input$samplesize_page4)
          #req(input$nchain_page4)
          req(input$timevar_page4)
          req(input$idvar_page4)
          req(input$pid_page4)
          
          idvar_page44<-input$idvar_page4
          pid_page44<-input$pid_page4
          P2<-predJRML(model=rv$model_page4,ids=pid_page44,dtlong=defaultlongdata_page4(),dtsurv=defaultsurvdata_page4())
          #rv$fileplotlong<-plot(P2$plong[[1]])
          plot(P2$plong[[1]])
        }else{
          req(input$samplesize_page4)
          #req(input$nchain_page4)
          req(input$timevar_page4)
          req(input$idvar_page4)
          req(input$pid_page44)
          
          idvar_page44<-input$idvar_page4
          pid_page441<-input$pid_page44
          P2<-predJRML(model=rv$model_page4,ids=pid_page441,dtlong=defaultlongdata_page4(),dtsurv=defaultsurvdata_page4())
          #rv$fileplotlong<-plot(P2$plong[[1]])
          plot(P2$plong[[1]])
          
        }
      })
    })
    
    observeEvent(input$submit_page4,{
      output$postSurvival<-renderPlot({
        
        if(input$data_option_page4 == "default"){
          req(input$samplesize_page4)
          #req(input$nchain_page4)
          req(input$timevar_page4)
          req(input$idvar_page4)
          req(input$pid_page4)
          
          idvar_page44<-input$idvar_page4
          pid_page44<-input$pid_page4
          P2<-predJRML(model=rv$model_page4,ids=pid_page44,dtlong=defaultlongdata_page4(),dtsurv=defaultsurvdata_page4())
          #rv$fileplotsurv<-plot(P2$psurv[[1]])
          plot(P2$psurv[[1]])
        }else{
          req(input$samplesize_page4)
          #req(input$nchain_page4)
          req(input$timevar_page4)
          req(input$idvar_page4)
          req(input$pid_page44)
          
          idvar_page44<-input$idvar_page4
          pid_page441<-input$pid_page44
          P2<-predJRML(model=rv$model_page4,ids=pid_page441,dtlong=defaultlongdata_page4(),dtsurv=defaultsurvdata_page4())
          #rv$fileplotsurv<-plot(P2$psurv[[1]])
          plot(P2$psurv[[1]])
          
        }
      })
    })
    
    
  },
  options = list(height=1000,width="100%")
)
```

jmstanBIG
=====================================  
  
  Column {data-width=1000}
-------------------------------------
```{r}
shinyApp(
  ui_page3 <- fluidPage(
    
    titlePanel("jmstanBig"),
    
    sidebarLayout(
      sidebarPanel(
        radioButtons("data_option_page3", "Select data source:",
                     c("Upload your own dataset" = "upload",
                       "Use default dataset from jmBIG" = "default")),
        conditionalPanel(
          condition = "input.data_option_page3 == 'default'",
          sliderInput("pid_page3", "ID", min = min(surv2$id), max = max(surv2$id), value = 50)
        ),
        conditionalPanel(
          condition = "input.data_option_page3 == 'upload'",
          fileInput("lfile_page3", "Upload Longitudinal Data (CSV format)"),
          fileInput("sfile_page3", "Upload Survival Data (CSV format)"), 
          uiOutput("pid_slider_upload_page3")
        ),
        selectInput("idvar_page3", "ID variable", choices =NULL),
        selectInput("timevar_page3", "Visit time", choices = NULL),
        selectInput('obs_time_page3',"Survival Time variable",choices=NULL),
        selectInput("event_page3", "Event status", choices = NULL),
        textInput("longmodel_page3", "Longitudinal data model", value = "y~visit+x7+(1|id)"),
        textInput("survmodel_page3", "Survival data model", value = "Surv(time,status)~1+x1"),
        numericInput("nchain_page3", "Number of chain", value = 1),
        numericInput("samplesize_page3", "Loop size", value = 200),
        actionButton("submit_page3", "Submit")
      ),
      mainPanel(
        p('jmstanBig(): a function for joint model in BIG DATA using rstanarm package. For more information about the arguments of the function please look ',a("here.",
                                                                                                                                                                href = "https://cran.r-project.org/web/packages/jmBIG/index.html")),
        textOutput('selected_var_page3'),
        textOutput('sample_size_page3'),
        verbatimTextOutput('summarylmemodel_page3'),
        textOutput('selectedID'),
        plotOutput('postTajectory'),
        plotOutput('postSurvival')
      )
    )
    
  ),
  
  server_page3 <- function(input, output, session) {
    
    #defaultsurvdata_page3<-NULL;defaultlongdata_page3<-NULL
    rv<-reactiveValues(model_page3=NULL)
    
    
    defaultsurvdata_page3 <- reactive({
      if (input$data_option_page3 == 'upload') {
        req(input$sfile_page3)
        defaultsurvdata_page3 <- read.csv(input$sfile_page3$datapath)
      } else {
        defaultsurvdata_page3 <- surv2
      }
      return(defaultsurvdata_page3)
    })
    
    
    
    observeEvent(defaultsurvdata_page3(), {
      updateSelectInput(session, "idvar_page3", choices = names(defaultsurvdata_page3()))
      updateSelectInput(session, "timevar_page3", choices = names(defaultsurvdata_page3()))
      updateSelectInput(session, "event_page3", choices = names(defaultsurvdata_page3()))
      updateSelectInput(session, "obs_time_page3", choices = names(defaultsurvdata_page3()))
      
      
    })
    
    defaultlongdata_page3 <- reactive({
      if (input$data_option_page3 == 'upload') {
        req(input$lfile_page3)
        defaultlongdata_page3 <- read.csv(input$lfile_page3$datapath)
      } else {
        defaultlongdata_page3 <- long2
      }
      return(defaultlongdata_page3)
    })
    
    # Render PID slider for uploaded data
    output$pid_slider_upload_page3 <- renderUI({
      req(input$idvar_page3)
      #req(defaultsuvdata_page3)
      tagList(
        selectInput("pid_page33", "Patient ID", choices=defaultsurvdata_page3()[[input$idvar_page3]],selectize = FALSE,size=5)
      )
    })
    
    output$selected_var_page3 <- reactive({
      
      if (input$data_option_page3 == "default") {
        req(input$pid_page3)
        paste("You have selected patient ID", input$pid_page3)
      } else {
        req(input$pid_page33)
        paste("Uploaded data selected with patient ID",input$pid_page33)
      }
    })
    
    output$selectedID <- reactive({
      
      if (input$data_option_page3 == "default") {
        req(input$pid_page3)
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmstanBig() for the selected patient ID: ', input$pid_page3)
      } else {
        req(input$pid_page33)
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmstanBig() for the selected patient ID: ',input$pid_page33)
      }
    })
    
    
    output$sample_size_page3 <- renderText({
      paste("Loop size for this computation is", input$samplesize_page3)
    })
    
    
    
    
    observeEvent(input$submit_page3,{
      # Load default data
      output$summarylmemodel_page3 <- renderPrint({
        req(input$samplesize_page3)
        req(input$nchain_page3)
        #req(defaultlongdata_page3)
        #req(defaultsurvdata_page3)
        req(input$longmodel_page3)
        req(input$survmodel_page3)
        req(input$timevar_page3)
        req(input$idvar_page3)
        
        
        
        longmodel3<-as.formula(input$longmodel_page3)
        survmodel3<-as.formula(input$survmodel_page3)
        
        
        fitmodel_page3 <- jmstanBig(dtlong = defaultlongdata_page3(), dtsurv = defaultsurvdata_page3(),
                                    longm =longmodel3, survm = survmodel3,
                                    time_var =input$timevar_page3, nchain = input$nchain_page3,
                                    samplesize = input$samplesize_page3,
                                    id =input$idvar_page3)
        rv$model_page3<-fitmodel_page3
        jmBIG::print(fitmodel_page3)
      })
      
    })
    
    observeEvent(input$submit_page3,{
      output$postTajectory<-renderPlot({
        
        if(input$data_option_page3=='default'){
          req(input$samplesize_page3)
          req(input$nchain_page3)
          req(input$timevar_page3)
          req(input$idvar_page3)
          req(input$pid_page3)
          
          idvar_page33<-input$idvar_page3
          #pid_page33<-input$pid_page3
          P2<-postTraj(model=rv$model_page3,m=1,ids=input$pid_page3)
          plot(P2$p1[[1]],plot_observed=TRUE)
        }else{
          req(input$samplesize_page3)
          req(input$nchain_page3)
          req(input$timevar_page3)
          req(input$idvar_page3)
          req(input$pid_page33)
          
          idvar_page33<-input$idvar_page3
          #pid_page331<-input$pid_page33
          P2<-postTraj(model=rv$model_page3,m=1,ids=input$pid_page33)
          plot(P2$p1[[1]],plot_observed=TRUE)
        }
        
        
      })
    })
    
    observeEvent(input$submit_page3,{
      output$postSurvival<-renderPlot({
        if(input$data_option_page3=='default'){
          req(input$samplesize_page3)
          req(input$nchain_page3)
          req(input$timevar_page3)
          req(input$idvar_page3)
          req(input$pid_page3)
          
          idvar_page33<-input$idvar_page3
          #pid_page33<-input$pid_page3
          P2<-postSurvfit(model=rv$model_page3,m=1,ids=input$pid_page3)
          plot(P2$p1[[1]])
        }else{
          req(input$samplesize_page3)
          req(input$nchain_page3)
          req(input$timevar_page3)
          req(input$idvar_page3)
          req(input$pid_page33)
          
          idvar_page33<-input$idvar_page3
          #pid_page33<-input$pid_page3
          P2<-postSurvfit(model=rv$model_page3,m=1,ids=input$pid_page33)
          plot(P2$p1[[1]])
        }
      })
    })
    
  },
  
  options = list(height=1000,width="100%")
)
```


jmcsBIG
=====================================  
  
  Column {data-width=1000}
-------------------------------------
```{r}
shinyApp(
  ui_page5 <- fluidPage(
    
    titlePanel("jmcsBIG"),
    
    sidebarLayout(
      sidebarPanel(
        radioButtons("data_option_page5", "Select data source:",
                     c("Upload your own dataset" = "upload",
                       "Use default dataset from jmBIG" = "default")),
        conditionalPanel(
          condition = "input.data_option_page5== 'default'",
          sliderInput("pid_page5", "ID", min = min(surv2$id), max = max(surv2$id), value = 50)
        ),
        conditionalPanel(
          condition = "input.data_option_page5== 'upload'",
          fileInput("lfile_page5", "Upload Longitudinal Data (CSV format)"),
          fileInput("sfile_page5", "Upload Survival Data (CSV format)"), 
          uiOutput("pid_slider_upload_page5")
        ),
        selectInput("idvar_page5", "ID variable", choices =NULL),
        selectInput("timevar_page5", "Visit time", choices = NULL),
        selectInput('obs_time_page5',"Survival Time variable",choices=NULL),
        selectInput('event_page5',"Event status",choices=NULL),
        textInput("longmodel_page5", "Longitudinal data model", value = "y~visit+x7"),
        textInput("rdmodel_page5", "Longitudinal data model random effect part", value = "~visit|id"),
        textInput("survmodel_page5", "Survival data model", value = "Surv(time,status)~visit+x1"),
        numericInput("samplesize_page5", "Loop size", value = 200),
        actionButton("submit_page5", "Submit")
      ),
      mainPanel(
        p('jmcsBig(): a function for joint model in BIG DATA using FastJM package. For more information about the arguments of the function please look ',a("here.",
                                                                                                                                                            href = "https://cran.r-project.org/web/packages/jmBIG/index.html")),
        textOutput('selected_var_page5'),
        textOutput('sample_size_page5'),
        verbatimTextOutput('summarylmemodel_page5'),
        #plotOutput('postTajectory'),
        textOutput('selectedID'),
        plotOutput('postSurvival')
      )
    )
    
  )
  ,
  
   server_page5 <- function(input, output, session) {
    
    
    defaultsurvdata_page5 <- reactive({
      if (input$data_option_page5 == 'upload') {
        req(input$sfile_page5)
        defaultsurvdata_page5 <- read.csv(input$sfile_page5$datapath)
      } else {
        defaultsurvdata_page5 <- surv2
      }
      return(defaultsurvdata_page5)
    })
    
    
    observeEvent(defaultsurvdata_page5(), {
      updateSelectInput(session, "idvar_page5", choices = names(defaultsurvdata_page5()))
      updateSelectInput(session, "timevar_page5", choices = names(defaultsurvdata_page5()))
      updateSelectInput(session, "obs_time_page5", choices = names(defaultsurvdata_page5()))
      updateSelectInput(session, "event_page5", choices = names(defaultsurvdata_page5()))
    })
    
    
    defaultlongdata_page5 <- reactive({
      if (input$data_option_page5 == 'upload') {
        req(input$lfile_page5)
        defaultlongdata_page5 <- read.csv(input$lfile_page5$datapath)
      } else {
        defaultlongdata_page5 <- long2
      }
      return(defaultlongdata_page5)
    })
    
    # Render PID slider for uploaded data
    output$pid_slider_upload_page5 <- renderUI({
      req(input$idvar_page5)
      tagList(
        selectInput("pid_page55", "Patient ID", choices=defaultsurvdata_page5()[[input$idvar_page5]],selectize = FALSE,size=5)
      )
    })
    
    output$selected_var_page5 <- reactive({
      
      if (input$data_option_page5 == "default") {
        req(input$pid_page5)
        paste("You have selected patient ID", input$pid_page5)
      } else {
        req(input$pid_page55)
        paste("Uploaded data selected with patient ID",input$pid_page55)
        
      }
    })
    
    output$selectedID <- reactive({
      
      if (input$data_option_page5 == "default") {
        req(input$pid_page5)
        paste('Prediction of survival probability learned from model fitted using jmcsBig() for the selected patient ID: ', input$pid_page5)
      } else {
        req(input$pid_page55)
        paste('Prediction of survival probability learned from model fitted using jmcsBig() for the selected patient ID: ',input$pid_page55)
        
      }
    })
    
    output$sample_size_page5 <- renderText({
      paste("Loop size for this computation is", input$samplesize_page5)
    })
    
    rv<-reactiveValues(model_page5=NULL)
    
    observeEvent(input$submit_page5,{
      # Load default data
      output$summarylmemodel_page5 <- renderPrint({
        req(input$samplesize_page5)
        #req(input$nchain)
        req(input$longmodel_page5)
        req(input$survmodel_page5)
        req(input$rdmodel_page5)
        req(input$timevar_page5)
        req(input$idvar_page5)
        
        rdmodel4<-as.formula(input$rdmodel_page5)
        longmodel4<-as.formula(input$longmodel_page5)
        survmodel4<-as.formula(input$survmodel_page5)
        
        fitmodel_page5 <- jmcsBig(dtlong = defaultlongdata_page5(), dtsurv = defaultsurvdata_page5(),
                                  longm = longmodel4, survm = survmodel4, rd = rdmodel4,
                                  samplesize = input$samplesize_page5,
                                  id = input$idvar_page5)
        rv$model_page5<-fitmodel_page5
        jmBIG::print(fitmodel_page5)
        
      })
      
    })
    
    
    observeEvent(input$submit_page5,{
      output$postSurvival<-renderPlot({
        
        
  survfitJMCS1<-function(model,ids,u,method='GH',obs.time){
  model1<-model
  model<-model$uprlist;ids<-ids
  nlength<-ids
  mlist<-list()
  mlonglist<-list()
  for(j in 1:length(model)){
    mlonglist[[j]]<-model[[j]]$cdata
  }
  f1<-function(x,id){as.numeric(id%in%x$id)}

  for(i in 1:length(ids)){
    mlist[[i]]<-sapply(mlonglist,f1,id=ids[i])
  }
  mc<-matrix(unlist(mlist),nrow=length(ids),ncol=length(model),byrow=T)
  idm<-apply(mc,1,function(x){which(x!=0)})

  p1<-list()
  for(k in 1:length(ids)){
    Mod11<-model[[idm[[k]][1]]]
    ynewdata<-Mod11$ydata[Mod11$ydata$id==ids[k],]
    cnewdata<-Mod11$cdata[Mod11$cdata$id==ids[k],]
    p1[[k]]<-survfitjmcs(Mod11,
                         ynewdata=ynewdata,
                         cnewdata=cnewdata,
                         u = u,seed=100,method=method,obs.time = obs.time)
  }

  P1<-Reduce('rbind',p1)
  #P1<-arrange(P1,desc(P1$id))
  result<-list()
  result$P1<-P1
  result$p1<-p1
  result$others<-list(jmcs_others=model1,obs.time=obs.time,ids=ids)
  class(result)<-"survfitJMCS"
  result
}
        
        
        if(input$data_option_page5 == "default"){
          req(input$samplesize_page5)
          #req(input$nchain_page5)
          req(input$timevar_page5)
          req(input$obs_time_page5)
          req(input$idvar_page5)
          req(input$pid_page5)
          req(input$longmodel_page5)
          req(input$survmodel_page5)
          req(input$rdmodel_page5)
          
          idvar_page55<-input$idvar_page5
          pid_page551<-input$pid_page5
          
          
          
          bootstrap_longitudinal_survival <- function(longitudinal_data, survival_data, n_bootstrap = 10,id,idNumber){
            bootstrap_samples <- vector("list", length = n_bootstrap)
            unique_ids <- as.numeric(unique(longitudinal_data[[id]]))
            for (i in 1:n_bootstrap) {
              # Sample IDs with replacement
              bootstrap_ids <- sample(unique_ids[unique_ids!=idNumber], replace = TRUE)
              n_bootstrap_ids<-seq(1,length(unique(survival_data[[id]])))
              
              
              bootstrap_longitudinal_sample <- data.frame()
              bootstrap_survival_sample <- data.frame()
              count<-0
              
              for (j in 1:(length(bootstrap_ids))) {
                
                id_longitudinal_data <- longitudinal_data[longitudinal_data[[id]] == bootstrap_ids[j], ]
                id_longitudinal_data[[id]]<-j
                id_survival_data <- survival_data[survival_data[[id]] == bootstrap_ids[[j]], ]
                id_survival_data[[id]]<-j
                bootstrap_longitudinal_sample <- rbind(bootstrap_longitudinal_sample, id_longitudinal_data)
                bootstrap_survival_sample <- rbind(bootstrap_survival_sample, id_survival_data)
              }
              newdatalong<-longitudinal_data[longitudinal_data[id]==idNumber,]
              newdatalong[id]<-length(unique(longitudinal_data[[id]]))
              bootstrap_longitudinal_sample<-rbind(bootstrap_longitudinal_sample,newdatalong)
              newdatasurv<-survival_data[survival_data[id]==idNumber,]
              newdatasurv[id]<-length(unique(longitudinal_data[[id]]))
              bootstrap_survival_sample<-rbind(bootstrap_survival_sample,newdatasurv)
              
              bootstrap_samples[[i]] <- list(longitudinal = bootstrap_longitudinal_sample, survival = bootstrap_survival_sample)
            }
            
            return(bootstrap_samples)
          }
          
          bootstrapped_data <- bootstrap_longitudinal_survival(defaultlongdata_page5(),
                                                               defaultsurvdata_page5(),
                                                               n_bootstrap = 10,id=input$idvar_page5,idNumber = input$pid_page5)
          fit2<-list();P2<-list();P3<-list()
          for(i in 1:10){
            P2<-survfitJMCS1(model=rv$model_page5,ids=pid_page551,u<-seq(defaultsurvdata_page5()[defaultsurvdata_page5()[idvar_page55]==pid_page551,][[input$obs_time_page5]],defaultsurvdata_page5()[defaultsurvdata_page5()[idvar_page55]==pid_page551,][[input$obs_time_page5]]+10,0.2),obs.time=input$obs_time_page5)
            fit2[[i]]<-jmcsBig(dtlong=data.frame(bootstrapped_data[[i]]$longitudinal),
                               dtsurv = data.frame(bootstrapped_data[[i]]$survival),
                               longm=as.formula(input$longmodel_page5),survm=as.formula(input$survmodel_page5),
                               rd= as.formula(input$rdmodel_page5),samplesize=200,id=input$idvar_page5)
            
            P2[[i]]<-survfitJMCS1(model<-fit2[[i]],ids<-c(1000),
                                 u<-seq(bootstrapped_data[[i]]$survival[bootstrapped_data[[i]]$survival[[idvar_page55]]==1000,][[input$obs_time_page5]],bootstrapped_data[[i]]$survival[bootstrapped_data[[i]]$survival[[idvar_page55]]==1000,][[input$obs_time_page5]]+10,0.2),obs.time=input$obs_time_page5)
            P3[[i]]<-P2[[i]]$P1$Pred$'1000'[,2]
            
          }
          
          CIdata<-Reduce('cbind',P3)
          qCIdata<-data.frame(Times=P2[[i]]$P1$Pred$'1000'$times,LL=apply(CIdata,1,function(x){quantile(x,0.025)}),Med=apply(CIdata,1,function(x){quantile(x,0.5)}),UL=apply(CIdata,1,function(x){quantile(x,0.975)}))
          survPlot<-ggplot(qCIdata, aes(x = Times, y = Med)) +
            geom_line() +
            geom_ribbon(aes(ymin = LL, ymax = UL), alpha = 0.3,fill='blue') +
            labs(title = "Survival Probabilities with Prediction Intervals",
                 x = "Time",
                 y = "Survival Probability") 
          survPlot
        }else{
          req(input$samplesize_page5)
          #req(input$nchain_page5)
          req(input$timevar_page5)
          req(input$idvar_page5)
          req(input$pid_page55)
          req(input$obs_time_page5)
          req(input$longmodel_page5)
          req(input$survmodel_page5)
          req(input$rdmodel_page5)
          idvar_page55<-input$idvar_page5
          pid_page551<-input$pid_page55
          lastid<-max(defaultsurvdata_page5()[[input$idvar_page5]])
          
          bootstrap_longitudinal_survival <- function(longitudinal_data, survival_data, n_bootstrap = 10,id,idNumber){
            bootstrap_samples <- vector("list", length = n_bootstrap)
            unique_ids <- as.numeric(unique(longitudinal_data[[id]]))
            for (i in 1:n_bootstrap) {
              # Sample IDs with replacement
              bootstrap_ids <- sample(unique_ids[unique_ids!=idNumber], replace = TRUE)
              n_bootstrap_ids<-seq(1,length(unique(survival_data[[id]])))
              
              
              bootstrap_longitudinal_sample <- data.frame()
              bootstrap_survival_sample <- data.frame()
              count<-0
              
              for (j in 1:(length(bootstrap_ids))) {
                
                id_longitudinal_data <- longitudinal_data[longitudinal_data[[id]] == bootstrap_ids[j], ]
                id_longitudinal_data[[id]]<-j
                id_survival_data <- survival_data[survival_data[[id]] == bootstrap_ids[[j]], ]
                id_survival_data[[id]]<-j
                bootstrap_longitudinal_sample <- rbind(bootstrap_longitudinal_sample, id_longitudinal_data)
                bootstrap_survival_sample <- rbind(bootstrap_survival_sample, id_survival_data)
              }
              newdatalong<-longitudinal_data[longitudinal_data[id]==idNumber,]
              newdatalong[id]<-length(unique(longitudinal_data[[id]]))
              bootstrap_longitudinal_sample<-rbind(bootstrap_longitudinal_sample,newdatalong)
              newdatasurv<-survival_data[survival_data[id]==idNumber,]
              newdatasurv[id]<-length(unique(longitudinal_data[[id]]))
              bootstrap_survival_sample<-rbind(bootstrap_survival_sample,newdatasurv)
              
              bootstrap_samples[[i]] <- list(longitudinal = bootstrap_longitudinal_sample, survival = bootstrap_survival_sample)
            }
            
            return(bootstrap_samples)
          }
          
          bootstrapped_data <- bootstrap_longitudinal_survival(defaultlongdata_page5(),
                                                               defaultsurvdata_page5(),
                                                               n_bootstrap = 10,id=input$idvar_page5,idNumber = input$pid_page55)
          fit2<-list();P2<-list();P3<-list();
          for(i in 1:10){
            P2<-try(survfitJMCS1(model=rv$model_page5,ids=pid_page551,u<-seq(defaultsurvdata_page5()[defaultsurvdata_page5()[idvar_page55]==pid_page551,][[input$obs_time_page5]],defaultsurvdata_page5()[defaultsurvdata_page5()[idvar_page55]==pid_page551,][[input$obs_time_page5]]+10,0.2),obs.time=input$obs_time_page5),silent=TRUE)
            fit2[[i]]<-try(jmcsBig(dtlong=data.frame(bootstrapped_data[[i]]$longitudinal),
                               dtsurv = data.frame(bootstrapped_data[[i]]$survival),
                               longm=as.formula(input$longmodel_page5),survm=as.formula(input$survmodel_page5),
                               rd= as.formula(input$rdmodel_page5),samplesize=200,id=input$idvar_page5),silent=TRUE)
            
            P2[[i]]<-try(survfitJMCS1(model<-fit2[[i]],ids<-c(lastid),
                                 u<-seq(bootstrapped_data[[i]]$survival[bootstrapped_data[[i]]$survival[[idvar_page55]]==lastid,][[input$obs_time_page5]],bootstrapped_data[[i]]$survival[bootstrapped_data[[i]]$survival[[idvar_page55]]==lastid,][[input$obs_time_page5]]+10,0.2),obs.time=input$obs_time_page5),silent=TRUE)
            P3[[i]]<-try(P2[[i]]$P1$Pred[[as.character(lastid)]][,2],silent=TRUE)
            
          }
          
          CIdata<-Reduce('cbind',P3)
          qCIdata<-data.frame(Times=P2[[i]]$P1$Pred[[as.character(lastid)]]$times,LL=apply(CIdata,1,function(x){quantile(x,0.025)}),Med=apply(CIdata,1,function(x){quantile(x,0.5)}),UL=apply(CIdata,1,function(x){quantile(x,0.975)}))
          survPlot<-ggplot(qCIdata, aes(x = Times, y = Med)) +
            geom_line() +
            geom_ribbon(aes(ymin = LL, ymax = UL), alpha = 0.3,fill='blue') +
            labs(title = "Survival Probabilities with Prediction Intervals",
                 x = "Time",
                 y = "Survival Probability") 
          survPlot
          
        }
        
        
      })
    })
    
  },
  
  options = list(height=1000,width="100%")
)
```


